version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Etc/UTC
    groups:
      dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-deps-ver:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      prod-deps-sec:
        applies-to: security-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "kuntzed"
      - "NiklasHerrmann21"
    open-pull-requests-limit: 10
