spring:
  security:
    oauth2:
      client:
        registration:
          myoauthserver:
            provider: myoauthserver
            client-id: ${vcap.services.spring-security-cas-authn.credentials.clientid}
            client-secret: ${vcap.services.spring-security-cas-authn.credentials.clientsecret}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          myoauthserver:
            #issuer-uri: https://xs2security.accounts400.ondemand.com
            issuer-uri: https://cp-application-security.authentication.sap.hana.ondemand.com/oauth/token